services:
  toggle:
    command: bash -c "sleep infinity"
    image: octree/decidim-dev:0.32
    entrypoint: ""
    working_dir: /home/module
    volumes:
      - .:/home/module
      - bundle:/home/decidim/vendor
      - node_modules:/home/decidim/node_modules
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://decidim:pleaseChangeMe@toggledb:5432/decidim
      - DATABASE_HOST=toggledb
      - DATABASE_USERNAME=decidim
      - DATABASE_PASSWORD=pleaseChangeMe
      - DEV_MODULE=decidim-toggle
      - RAILS_ENV=development
      - DISABLED_DOCKER_COMPOSE=true
      - DECIDIM_FORCE_SSL=false
      - RAILS_FORCE_SSL=false
    depends_on:
      toggledb:
        condition: service_healthy
    ports:
      - 3000:3000

  toggledb:
    image: postgres:17
    volumes:
      - toggle-pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DATABASE=decidim
      - POSTGRES_USER=decidim
      - POSTGRES_PASSWORD=pleaseChangeMe
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U decidim"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  node_modules: {}
  bundle: {}
  toggle-pg-data: {}
